const allData = [
  {
    id: 1,
    name: "Home",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
      { id: 1, userId: 1, subName: "Aerobot", description: "No Data" },
      { id: 2, userId: 1, subName: "To Do", description: "No Data" },
      { id: 3, userId: 1, subName: "My Dashboard", description: "No Data" },
      { id: 4, userId: 1, subName: "Messenger", description: "No Data" },
      { id: 5, userId: 1, subName: "Maps", description: "No Data" },
      { id: 6, userId: 1, subName: "Notifications", description: "No Data" },
      { id: 7, userId: 1, subName: "Data Sources", description: "No Data" },
      { id: 8, userId: 1, subName: "Settings", description: "No Data" },
    ],
  },
  {
    id: 2,
    name: "Operations",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 2, subName: "Dashboard", description: "" },
        {
          id: 2,
          userId: 2,
          subName: "Airfield Condition Reporting",
          description: "",
        },
        { id: 3, userId: 2, subName: "Operations Log", description: "" },
        { id: 4, userId: 2, subName: "Phonebook", description: "" },
        { id: 5, userId: 2, subName: "Dashboard", description: "" },
      ],
  },
  {
    id: 3,
    name: "Inspections",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 3, subName: "Inspections", description: "" },
        { id: 2, userId: 3, subName: "Bulk Export", description: "" },
        { id: 3, userId: 3, subName: "Settings", description: "" },
      ],
  },
  {
    id: 4,
    name: "Work Orders",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 4, subName: "Dashboard", description: "" },
        { id: 2, userId: 4, subName: "Airfield Work Orders", description: "" },
        {
          id: 3,
          userId: 4,
          subName: "Non-Airfield Work Orders",
          description: "",
        },
        {
          id: 4,
          userId: 4,
          subName: "Preventative Maintenance",
          description: "",
        },
        { id: 5, userId: 4, subName: "Settings", description: "" },
      ],
  },
  {
    id: 5,
    name: "Asset Managment",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 5, subName: "Dashboard", description: "" },
        { id: 2, userId: 5, subName: "Asset Registry", description: "" },
        { id: 3, userId: 5, subName: "Airfield Assets", description: "" },
        { id: 4, userId: 5, subName: "Lanside Assets", description: "" },
        { id: 5, userId: 5, subName: "Inventory", description: "" },
        { id: 6, userId: 5, subName: "Settings", description: "" },
      ],
  },
  {
    id: 6,
    name: "Shift Managment",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 6, subName: "Tasks", description: "" },
        { id: 2, userId: 6, subName: "Assigment", description: "" },
      ],
  },
  {
    id: 7,
    name: "WildLife",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 7, subName: "Dashboard", description: "" },
        { id: 2, userId: 7, subName: "Wildlife Log", description: "" },
        { id: 3, userId: 7, subName: "Settings", description: "" },
      ],
  },
  {
    id: 8,
    name: "Lease Managment",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 8, subName: "Dashboard", description: "" },
        { id: 2, userId: 8, subName: "Properties", description: "" },
        {
          id: 3,
          userId: 8,
          subName: "Non-Airfield Work Orders",
          description: "",
        },
        { id: 4, userId: 8, subName: "Invoices", description: "" },
        { id: 5, userId: 8, subName: "Tenants", description: "" },
        { id: 6, userId: 8, subName: "Hangar Inspections", description: "" },
        { id: 7, userId: 8, subName: "Contacts", description: "" },
        { id: 8, userId: 8, subName: "Based AirCrafts", description: "" },
        { id: 9, userId: 8, subName: "Portal", description: "" },
        { id: 10, userId: 8, subName: "Settings", description: "" },
      ],
  },
  {
    id: 9,
    name: "Portal",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 9, subName: "Tenant Portal", description: "" },
        { id: 2, userId: 9, subName: "Portal Users", description: "" },
      ],
  },
  {
    id: 10,
    name: "Training Managment",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 10, subName: "Dashboard", description: "" },
        { id: 2, userId: 10, subName: "Training Log", description: "" },
        { id: 3, userId: 10, subName: "Settings", description: "" },
      ],
  },
  {
    id: 11,
    name: "FOD Log",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 11, subName: "Dashboard", description: "" },
        { id: 2, userId: 11, subName: "FOD Log", description: "" },
        { id: 3, userId: 11, subName: "Settings", description: "" },
      ],
  },
  {
    id: 12,
    name: "Forms",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 12, subName: "Forms", description: "" },
        { id: 2, userId: 12, subName: "Form Data", description: "" },
        { id: 3, userId: 12, subName: "Settings", description: "" },
      ],
  },
  {
    id: 13,
    name: "Noise Managment",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 13, subName: "Dashboard", description: "" },
        { id: 2, userId: 13, subName: "Noise Log", description: "" },
        { id: 3, userId: 13, subName: "Settings", description: "" },
      ],
  },
  { id: 14, name: "SMS", iconLeft: "", iconRight: "fa-solid fa-angle-right",
  subMenu: [
    { id: 1, userId: 14, subName: "Dashboard", description: "" },
    { id: 2, userId: 14, subName: "Risk Register", description: "" },
    { id: 3, userId: 14, subName: "Corrective Actions", description: "" },
    { id: 4, userId: 14, subName: "Settings", description: "" },
  ],
    },
  {
    id: 15,
    name: "Badge Management",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
    subMenu: [
        { id: 1, userId: 15, subName: "Badges", description: "" },
        { id: 2, userId: 15, subName: "Settings", description: "" },
      ],
  },
  { id: 16, name: "LMS", iconLeft: "", iconRight: "fa-solid fa-angle-right", 
  subMenu: [
    { id: 1, userId: 16, subName: "Calendar", description: "" },
    { id: 2, userId: 16, subName: "My Trainings", description: "" },
    { id: 3, userId: 16, subName: "Manage Trainings", description: "" },
    { id: 4, userId: 16, subName: "Logs", description: "" },
    { id: 5, userId: 16, subName: "Settings", description: "" },
  ],
},
  {
    id: 17,
    name: "Gate Managment",
    iconLeft: "",
    iconRight: "fa-solid fa-angle-right",
  },
];

export default allData;
